apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
        - image: docker.io/gengiskhan3/argocdwebapp:latest
          imagePullPolicy: Always
          name: app-2048
          ports:
            - containerPort: 80
